### PR TITLE
Fix missing Flux/Influxdb versions

### LINKED ISSUE #5239: Flux versions page out of date
https://docs.influxdata.com/flux/v0/influxdb-versions/

1.11.3  Enterprise has been released, and includes Flux 0.194.3

### PR DESCRIPTION
**Pull request by sanderson**
Closes #5239

This fixes an issue that was preventing all InfluxDB Enterprise versions from being listed in the Flux/InfluxDB versions list. It had to do with how versions were being filtered using straight float comparisons instead of comparing each level of the semantic version.

This introduced a display bug that would cause 2+ digit minor versions to show up after 1-digit minor versions. I hacked together a fix for this that works for the time being by just filtering minor versions based on their length.

- [x] Rebased/mergeable

### CODE REVIEW

File: flux-build-scripts/update-flux-versions.js [hunk 1]
```diff
@@ -70,13 +70,27 @@ function addVersion(versionObj, influxdbVer, fluxVer) {
...
 // Load product data from the product data file
 const productData = yaml.load(fs.readFileSync(path.resolve(__dirname,'../data/products.yml'), 'utf8'))
 
-// Update InfluxDB version arrays by removing 'v' from each version and filtering
-// out InfluxDB versions that don't have a Flux dependency in their go.mod
-const ossVersionArr = productData.influxdb.minor_versions.map((element, index) => {return element.replace('v', '')}).filter(element => parseFloat(element) >= 1.7).reverse();
-const enterpriseVersionArr = productData.enterprise_influxdb.minor_versions.map((element, index) => {return element.replace('v', '')}).filter(element => parseFloat(element) >= 1.9).reverse();
+// Update InfluxDB version arrays by removing 'v' from each version
+// Filter out InfluxDB versions that don't have a Flux dependency in their go.mod
+const ossVersionArr = productData.influxdb.minor_versions.map((element) => {return element.replace('v', '')}).filter(version => isSemanticNewer(version, '1.7'));
```
Comment (jstirnaman) [inline flux-build-scripts/update-flux-versions.js:92]: Why the "magic numbers?"

File: flux-build-scripts/update-flux-versions.js [hunk 2]
```diff
@@ -70,13 +70,27 @@ function addVersion(versionObj, influxdbVer, fluxVer) {
...
+const enterpriseVersionArr = productData.enterprise_influxdb.minor_versions.map((element) => {return element.replace('v', '')}).filter(version => isSemanticNewer(version, '1.9'));
```
Comment (jstirnaman) [inline flux-build-scripts/update-flux-versions.js:93]: Magic number

File: flux-build-scripts/update-flux-versions.js [hunk 3]
```diff
@@ -89,7 +103,7 @@ var fluxVersions = {};
   await getAllFluxVersions(enterpriseVersionArr, 'enterprise', enterpriseVersions);
 
   // Manually add versions that aren't included in the original versions arrays
-  await addVersion(ossVersions, 'nightly', await getFluxVersion('master'));
+  await addVersion(ossVersions, 'nightly', await getFluxVersion('2.7'));
   await addVersion(enterpriseVersions, '1.8', await getFluxVersion('1.8'));
   await addVersion(enterpriseVersions, '1.7', await getFluxVersion('1.7'));
```
Comment (jstirnaman) [inline flux-build-scripts/update-flux-versions.js:108]: More magic numbers?

**Review by jstirnaman — APPROVED** [review]
Looks good. Just wondering why you're setting the version numbers in the code and not using the config?

File: flux-build-scripts/update-flux-versions.js (hunk 2 above)
Comment (sanderson) [reply flux-build-scripts/update-flux-versions.js:93]: 1.9 is the version of Enterprise that started getting regular updates with Flux and Flux was added to the `go.mod`. The other versions of enterprise have fixed versions.

File: flux-build-scripts/update-flux-versions.js (hunk 3 above)
Comment (sanderson) [reply flux-build-scripts/update-flux-versions.js:108]: I didn't know what to do here. The `master` branch is no longer maintained (because the switched the primary branch to `main`) and the v2 nightlies are being build from the 2.7 branch.
