### PR TITLE
Fix/2759 1.x query api

### LINKED ISSUE #2759: Improve query docs (api and task-based)
Folks are struggling with how to use `/query` 1.x compatibility API, including running into "unauthorized" requests bc authentication isn't set up properly. Also, folks who want to use InfluxQL who are not coming from 1.x...still need to include a database/rp in the query, which is a bit unintuitive (given the bucket_id is also required).

Some specific updates for https://docs.influxdata.com/influxdb/cloud/reference/api/influxdb-1x/query:
- basic vs token auth (when/why you'd use one or the other)
- clarity on `-u`/`-p` parameters vs `-user` (requires Cloud username/pass, not 1.x username/pass)
- add `--user` as parameter
- include comments in query examples to reflect type of auth and credentials needed (can we automatically update examples re selected authentication method?).

Some specific updates for https://docs.influxdata.com/influxdb/cloud/query-data/influxql/:
- Layer in/link to "mapping buckets" --this is a once and done, which wouldn't need to be completed as part of this procedure every time.
- Some folks may query data with InfluxQL without coming from a 1.x background, in these cases, it's important to note that if you have an existing bucket that doesn’t follow the database/retention-policy naming convention, you must manually create a database and retention policy mapping to query that bucket with the /query compatibility API.

cc @rbetts for review

### PR DESCRIPTION
**Pull request by jstirnaman**
Closes #2759

Clarify authentication schemes and options for 1.x compatibility API in OSS and Cloud.
Fix errors.
Add code examples.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

### CODE REVIEW

**Comment by jstirnaman** [comment]
@sanderson I especially need your eyes on changes in assets/js/influxdb-url.js to replace hostnames in addition to full URLs

File: assets/text/api/v1-compat/auth/cloud/basic-auth.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+/**
+  * Use an InfluxDB Cloud username and token
+  * with Basic Authentication
+  * to query the InfluxDB 1.x-compatibility API
+  */
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/cloud/basic-auth.js:5]: When rendered, the actual code feels crowded by the comment. I'd just suggest adding new lines after the comment blocks in these code examples.

```suggestion
  */

```

File: assets/text/api/v1-compat/auth/cloud/basic-auth.sh [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+# Use an InfluxDB 1.x compatible username
+# and password with Basic Authentication
+# to query the InfluxDB 1.x-compatibility API
+#######################################
+# Use default retention policy
+#######################################
+# Use the --user option with `--user <username>:<password>` syntax
+# or the `--user <username>` interactive syntax to ensure your credentials are
+# encoded in the header.
+#######################################
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/cloud/basic-auth.sh:11]:
```suggestion
#######################################

```

File: assets/text/api/v1-compat/auth/oss/basic-auth.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
+/**
+  * Use an InfluxDB 1.x compatible username and password
+  * to query the InfluxDB 1.x-compatibility API
+  *
+  * Use Basic authentication
+  */
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/oss/basic-auth.js:6]:
```suggestion
  */

```

File: assets/text/api/v1-compat/auth/oss/basic-auth.sh [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+# Use an InfluxDB 1.x compatible username
+# and password with Basic Authentication
+# to query the InfluxDB 1.x-compatibility API
+#######################################
+# Use default retention policy
+#######################################
+# Use the --user option with `--user <username>:<password>` syntax
+# or the `--user <username>` interactive syntax to ensure your credentials are
+# encoded in the header.
+#######################################
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/oss/basic-auth.sh:11]:
```suggestion
#######################################

```

Something to think about – the content currently in these comments may be more readable outside of the code block as paragraph text.

File: assets/text/api/v1-compat/auth/oss/querystring-auth.sh [hunk 5]
```diff
@@ -0,0 +1,13 @@
+#######################################
+# Use an InfluxDB 1.x compatible username and password
+# to query the InfluxDB 1.x-compatibility API
+#######################################
+# Use authentication query parameters:
+#   ?u=<username>&p=<password>
+# Use default retention policy.
+#######################################
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/oss/querystring-auth.sh:8]:
```suggestion
#######################################

```

File: assets/text/api/v1-compat/auth/oss/token-auth.js [hunk 6]
```diff
@@ -0,0 +1,34 @@
+/**
+  * Use a token in the Authorization header
+  * to query the InfluxDB 1.x-compatibility API
+  */
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/oss/token-auth.js:4]:
```suggestion
  */

```

File: assets/text/api/v1-compat/auth/oss/token-auth.sh [hunk 7]
```diff
@@ -0,0 +1,9 @@
+#######################################
+# Use a token in the Authorization header
+# to query the InfluxDB 1.x-compatibility API
+#######################################
```
Comment (sanderson) [inline assets/text/api/v1-compat/auth/oss/token-auth.sh:4]:
```suggestion
#######################################

```

File: content/influxdb/cloud/reference/api/influxdb-1x/_index.md [hunk 8]
```diff
@@ -21,40 +21,127 @@ like [Grafana](https://grafana.com) and others.
...
+#### Query string authentication
+Use InfluxDB 1.x API parameters to provide username and password credentials through the query string.
+
+{{% note %}}
+##### Using query string parameters
+
+* URL-encode query parameters that may contain whitespace or other special characters.
+
+* Be aware of the <a href="https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url">risks</a> when exposing sensitive data through URLs.
+{{% /note %}}
```
Comment (sanderson) [inline content/influxdb/cloud/reference/api/influxdb-1x/_index.md:118]:
```suggestion
{{% note %}}
##### Consider when using query string parameters

- URL-encode query parameters that may contain whitespace or other special characters.
- Be aware of the [risks](https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url) when exposing sensitive data through URLs.
{{% /note %}}
```

File: content/influxdb/cloud/reference/api/influxdb-1x/query.md [hunk 9]
```diff
@@ -18,4 +18,121 @@ related:
...
 ---
 
-{{< duplicate-oss >}}
\ No newline at end of file
+The `/query` 1.x compatibility endpoint queries InfluxDB Cloud and InfluxDB OSS 2.0 using **InfluxQL**.
+Use the `GET` request method to query data from the `/query` endpoint.
+
+<pre>
+<span class="api get">GET</span> http://localhost:8086/query
+</pre>
```
Comment (sanderson) [inline content/influxdb/cloud/reference/api/influxdb-1x/query.md:26]:
```suggestion
{{< api-endpoint method="get" endpoint="http://localhost:8086/query" >}}
```

File: content/influxdb/cloud/reference/api/influxdb-1x/write.md [hunk 10]
```diff
@@ -19,4 +19,109 @@ related:
...
-{{< duplicate-oss >}}
\ No newline at end of file
+The `/write` 1.x compatibility endpoint writes data to InfluxDB Cloud and InfluxDB OSS 2.0
+using patterns from the InfluxDB 1.x `/write` API endpoint.
+Use the `POST` request method to write [line protocol](/influxdb/cloud/reference/syntax/line-protocol/)
+to the `/write` endpoint.
+
+<pre>
+<span class="api post">POST</span> https://cloud2.influxdata.com/write
+</pre>
```
Comment (sanderson) [inline content/influxdb/cloud/reference/api/influxdb-1x/write.md:29]:
```suggestion
{{< api-endpoint method="post" endpoint="https://cloud2.influxdata.com/write" >}}
```

File: content/influxdb/v2.0/install.md [hunk 11]
```diff
@@ -134,6 +134,22 @@ To manually authorize the InfluxDB binaries:
...
+After running `influxd`, you might see an error in the log output like the
+following:
+
+```sh
+too many open files
+```
+
+To resolve this error, follow the
+ [recommended steps](https://unix.stackexchange.com/a/221988/471569) to increase
+  file and process limits for your operating system version then restart `influxd`.
```
Comment (sanderson) [inline content/influxdb/v2.0/install.md:149]:
```suggestion
To resolve this error, follow the
[recommended steps](https://unix.stackexchange.com/a/221988/471569) to increase
file and process limits for your operating system version then restart `influxd`.
```

File: content/influxdb/v2.0/reference/api/influxdb-1x/_index.md [hunk 12]
```diff
@@ -20,46 +20,134 @@ InfluxDB 1.x client libraries and third-party integrations like [Grafana](https:
...
-```sh
-# Header syntax
-Authorization: Token <token>
+{{% note %}}
+##### Using query string parameters
+
+* URL-encode query parameters that may contain whitespace or other special characters.
+
+* Be aware of the <a href="https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url">risks</a> when exposing sensitive data through URLs.
+{{% /note %}}
```
Comment (sanderson) [inline content/influxdb/v2.0/reference/api/influxdb-1x/_index.md:124]:
```suggestion
##### Consider when using query string parameters

- URL-encode query parameters that may contain whitespace or other special characters.
- Be aware of the [risks](https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url) when exposing sensitive data through URLs.
{{% /note %}}
```

File: content/influxdb/v2.0/reference/api/influxdb-1x/_index.md [hunk 13]
```diff
@@ -20,46 +20,134 @@ InfluxDB 1.x client libraries and third-party integrations like [Grafana](https:
...
+```sh
+{{< get-assets-text "api/v1-compat/auth/oss/querystring-auth.sh" >}}
+```
+{{% /code-tab-content %}}
+{{% code-tab-content %}}
+```js
+{{< get-assets-text "api/v1-compat/auth/oss/querystring-auth.js" >}}
 ```
+{{% /code-tab-content %}}
+{{% /code-tabs-wrapper %}}
```
Comment (sanderson) [inline content/influxdb/v2.0/reference/api/influxdb-1x/_index.md:150]:
~~~suggestion
{{< code-tabs-wrapper >}}
{{% code-tabs %}}
[curl](#curl)
[Node.js](#nodejs)
{{% /code-tabs %}}
{{% code-tab-content %}}
```sh
{{< get-assets-text "api/v1-compat/auth/oss/querystring-auth.sh" >}}
```
{{% /code-tab-content %}}
{{% code-tab-content %}}
```js
{{< get-assets-text "api/v1-compat/auth/oss/querystring-auth.js" >}}
```
{{% /code-tab-content %}}
{{< /code-tabs-wrapper >}}
~~~

File: content/influxdb/v2.0/reference/api/influxdb-1x/write.md [hunk 14]
```diff
@@ -46,10 +51,10 @@ encode the line protocol.
 ## Query string parameters
 
 ### u
-(Optional) The 1.x **username** to authenticate the request.
+(Optional) The 1.x **username** to authenticate the request. For more information, see [query string authentication](/influxdb/v2.0/reference/api/influxdb-1x/#query-string-authentication)
```
Comment (sanderson) [inline content/influxdb/v2.0/reference/api/influxdb-1x/write.md:54]:
```suggestion
(Optional) The 1.x **username** to authenticate the request. For more information, see [query string authentication](/influxdb/v2.0/reference/api/influxdb-1x/#query-string-authentication).
```

File: content/influxdb/v2.0/reference/api/influxdb-1x/write.md [hunk 15]
```diff
@@ -46,10 +51,10 @@ encode the line protocol.
...
 
 ### p
-(Optional) The 1.x **password** to authenticate the request.
+(Optional) The 1.x **password** to authenticate the request. For more information, see [query string authentication](/influxdb/v2.0/reference/api/influxdb-1x/#query-string-authentication)
```
Comment (sanderson) [inline content/influxdb/v2.0/reference/api/influxdb-1x/write.md:57]:
```suggestion
(Optional) The 1.x **password** to authenticate the request. For more information, see [query string authentication](/influxdb/v2.0/reference/api/influxdb-1x/#query-string-authentication).
```

File: content/influxdb/cloud/reference/api/influxdb-1x/write.md [hunk 16]
```diff
@@ -19,4 +19,109 @@ related:
...
+The examples [below](#write-examples) use the curl `--data-binary` flag to binary
+encode the line protocol.
+
+## Query string parameters
+
+### u
+(Optional) The InfluxDB Cloud **username** to authenticate the request. For more information, see [query string authentication](/influxdb/cloud/reference/api/influxdb-1x/#query-string-authentication)
+
+### p
+(Optional) The InfluxDB Cloud **authentication token** to authenticate the request. For more information, see [query string authentication](/influxdb/cloud/reference/api/influxdb-1x/#query-string-authentication)
```
Comment (sanderson) [inline content/influxdb/cloud/reference/api/influxdb-1x/write.md:53]:
```suggestion
(Optional) The InfluxDB Cloud **authentication token** to authenticate the request. For more information, see [query string authentication](/influxdb/cloud/reference/api/influxdb-1x/#query-string-authentication).
```

File: content/influxdb/cloud/reference/api/influxdb-1x/write.md [hunk 17]
```diff
@@ -19,4 +19,109 @@ related:
...
+## Request body
+Include your line protocol in the request body.
+**Binary encode** the line protocol to prevent unintended formatting.
+The examples [below](#write-examples) use the curl `--data-binary` flag to binary
+encode the line protocol.
+
+## Query string parameters
+
+### u
+(Optional) The InfluxDB Cloud **username** to authenticate the request. For more information, see [query string authentication](/influxdb/cloud/reference/api/influxdb-1x/#query-string-authentication)
```
Comment (sanderson) [inline content/influxdb/cloud/reference/api/influxdb-1x/write.md:50]:
```suggestion
(Optional) The InfluxDB Cloud **username** to authenticate the request. For more information, see [query string authentication](/influxdb/cloud/reference/api/influxdb-1x/#query-string-authentication).
```

File: content/influxdb/v2.0/reference/cli/influx/v1/auth/_index.md [hunk 18]
```diff
@@ -13,12 +13,11 @@ influxdb/v2.0/tags: [authorization]
 The `influx v1 auth` subcommands provide authorization management for the
 [InfluxDB 1.x compatibility API](/influxdb/v2.0/reference/api/influxdb-1x/).
 
-InfluxDB 2.0 requires authorization with token-based authorization as the standard method.
-The [1.x compatibility API](/influxdb/v2.0/reference/api/influxdb-1x/) lets clients
-authenticate with InfluxDB 2.0 using the InfluxDB 1.x convention of username and password.
+InfluxDB 2.0 {{% cloud-token-auth %}}
+The [1.x compatibility API](/influxdb/v2.0/reference/api/influxdb-1x/) allows clients to authenticate with InfluxDB 2.0 using the InfluxDB 1.x convention of username and password.
```
Comment (sanderson) [inline content/influxdb/v2.0/reference/cli/influx/v1/auth/_index.md:17]:
```suggestion
The [1.x compatibility API](/influxdb/v2.0/reference/api/influxdb-1x/) lets clients authenticate with InfluxDB 2.0 using the InfluxDB 1.x convention of username and password.
```

File: layouts/shortcodes/cloud-token-auth.html [hunk 19]
```diff
@@ -0,0 +1 @@
+requires all requests to be authenticated with **token authentication**.
```
Comment (sanderson) [inline layouts/shortcodes/cloud-token-auth.html:1]: Link token authentication to an example.

**Review by sanderson — CHANGES_REQUESTED** [review]
Some nits. Overall, this looks great.

File: assets/text/api/v1-compat/auth/oss/basic-auth.sh (hunk 4 above)
Comment (jstirnaman) [reply assets/text/api/v1-compat/auth/oss/basic-auth.sh:11]: Debated that, but went with the comment since it's specific to curl

File: content/influxdb/v2.0/reference/api/influxdb-1x/_index.md (hunk 13 above)
Comment (jstirnaman) [reply content/influxdb/v2.0/reference/api/influxdb-1x/_index.md:150]: Arrgggh... thought I got them all.
